Controllers/ChatsController.cs
using airbnb.Data;
using airbnb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Vereyon.Web;

namespace airbnb.Controllers;

public class ChatsController : Controller
{

    private readonly ApplicationDbContext _context;
    private readonly IFlashMessage _flashMessage;
    
    public ChatsController(ApplicationDbContext context, IFlashMessage flashMessage)
    {
        _context = context;
        _flashMessage = flashMessage;
    }

    public IActionResult Index()
    {
        if (User.Identity == null || !User.Identity.IsAuthenticated)
        {
            _flashMessage.Danger("You have to log in to access this page.");
            return RedirectToAction("Index", "Index");
        }
        
        var chats = from c in _context.Chats
                .Include(c => c.User1)
                .Include(c => c.User2)
                .Where(c => c.User1.UserName == User.Identity.Name || c.User2.UserName == User.Identity.Name)
                .Include(c => c.Messages)
            select c;
        var orderedChats = chats
            .ToList()
            .OrderBy(chat => chat.Messages.MaxBy(m => m.Timestamp).Timestamp)
            .Reverse();
        return View(orderedChats);
    }

    public async Task<IActionResult> Details(int id)
    {
        if (User.Identity == null || !User.Identity.IsAuthenticated)
        {
            _flashMessage.Danger("You have to log in to access this page.");
            return RedirectToAction("Index", "Index");
        }
    
        var chat = await _context.Chats
            .Include(c => c.User1)
            .Include(c => c.User2)
            .Include(c => c.Messages)
            .ThenInclude(m => m.Author)
            .FirstOrDefaultAsync(m => m.Id == id);
        
        if (chat == null)
        {
            return NotFound();
        }

        return View(chat);
    }

    [HttpPost]
    public async Task<IActionResult> CreateMessage(       
        [Bind("ChatId", "AuthorUserName", "Text")]
        MessageCreateViewModel messageCreateViewModel)
    {
        if (User.Identity == null || !User.Identity.IsAuthenticated || messageCreateViewModel.AuthorUserName != User.Identity.Name)
        {
            return Unauthorized();
        }
        User user = _context.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);
        
        var chat = await _context.Chats
            .Include(c => c.User1)
            .Include(c => c.User2)
            .FirstOrDefaultAsync(m => m.Id == messageCreateViewModel.ChatId);
        if (chat == null)
        {
            return NotFound();
        }

        if (chat.User1 != user && chat.User2 != user)
        {
            return Unauthorized();
        }
        
        var message = new Message
        {
            Chat = chat,
            Author = user,
            Timestamp = DateTime.Now,
            Text = messageCreateViewModel.Text
        };
        _context.Add(message);
        
        _context.SaveChanges();

        return RedirectToAction("Details", new { chat.Id });
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - airbnb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/airbnb.styles.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/lib/daterangepicker/daterangepicker.css" asp-append-version="true"/>
</head>
<body style="background-color: #f3f4f6">
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Index" asp-action="Index">airbnb</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Index" asp-action="Index">Find a home</a>
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Homes" asp-action="Create">Host your home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Homes" asp-action="UserHomes">Your homes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bookings" asp-action="Index">Bookings</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Chats" asp-action="Index">Messages</a>
                        </li>
                    }
                </ul>
                <partial name="_LoginPartial"/>
            </div>
        </div>
    </nav>
</header>
<div id="flash-notifications" class="mx-auto" style="margin-left: 80px; margin-right: 80px; max-width: 1320px;">
    @addTagHelper *, Vereyon.Web.FlashMessage 
    <flash dismissable="true"/>
</div>
<div class="container shadow-lg p-3 mb-5 rounded" style="background-color: white; margin-top: 50px;">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<hr/>
<footer class="border-top footer text-muted" style="margin-top: 60px">
    <div class="container">
        &copy; 2022 - airbnb - <a asp-area="" asp-controller="Index" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/lib/daterangepicker/moment.min.js"></script>
<script src="~/lib/daterangepicker/daterangepicker.js"></script>

<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>